server:
  port: 8086
spring:
  application:
    name: feign-inherit-consumer
eureka:
  client:
    service-url:
      defaultZone: http://codeshop:codeshop@localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}